name: Pre-merge Check

on:
  pull_request:
    branches: [ dev ]
    paths:
     - docs/**

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: Install Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.10.12
          - name: Pull latest code
            run: |
                  git checkout dev
                  git pull origin dev
                  git checkout ${{github.head_ref}}
                  git pull origin ${{github.head_ref}}

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
          - name: Execute pre-merged script
            env:
                GITHUB_TOKEN: ${{ secrets.MASTER_GITHUB_TOKEN }}
                SLACK_WEB_HOOK: ${{ secrets.SLACK_WEB_HOOK }}
                PR_NUMBER: ${{ github.event.number }}
                CURRENT_BRANCH: ${{ github.head_ref }}
                USER_EMAIL: ${{ secrets.USER_EMAIL }}
            run: python script_v2/pre-merge.py
