name: Lint

on:
  pull_request:
    branches: main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g markdownlint-cli

      - name: Lint Markdown
        run: markdownlint --fix **/*.md

      - name: Commit Change
        run: |
            git add .
            git commit -m "Syntax: Fixing lint issue"
            git push
