name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: 'blogs/*.md,library/*.md'
          separator: ','
          config: custom.markdownlint.yaml
